#
# Jekyll configuration
#
auto:        true

#
# Site configuration
#
url:          http://genevajug.ch
title:        GenevaJUG
description:  Geneva Java User Group Website
keywords:     Geneva, Java, JUG
author:       # atom.xml: Name of website's author
email:        # atom.xml: Author email
analytics_id: UA-20372950-1
