#
# Jekyll configuration
#
# Auto-regeneration no more supported. Have to use --watch on the command line instead.
# See http://jekyllrb.com/docs/configuration/
# auto:        true        
encoding: UTF-8
#
# Site configuration
#
url:          http://genevajug.ch
title:        GenevaJUG
description:  Geneva Java User Group Website
keywords:     Geneva, Java, JUG
author:       # atom.xml: Name of website's author
email:        # atom.xml: Author email
analytics_id: UA-20372950-1

collections:
  main:
  events:
    output: true
  speakers:
    output: true
  sponsors_premium:
    output: true
  sponsors_saison:
    output: true
  sponsoring:
    output: true
