# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geneva Jug
email: 
description: > # this means to ignore newlines until "baseurl:"
  Le GenevaJUG est un groupe d’utilisateurs Java ayant pour but de réunir les acteurs du langage (professionnels, communautés open source, institutions, étudiants, enseignants…) afin d’échanger des idées et de discuter des avancées technologiques de la plateforme Java.
  Nous nous rencontrons le dernier mardi du mois. Les réunions sont gratuites, ouvertes à tous et consistent en une présentation technique, une démonstration d’un produit, ou une table ronde. Après la réunion nous nous retrouvons généralement pour un échange informel autour d’un verre et d’un mini-buffet. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yaucheres,github.io" # the base hostname & protocol for your site
twitter_username: genevaJug
github_username:  GenevaJug
slogan: // Java dans tous ses états
permalink: /events/:title:output_ext
# Build settings
markdown: kramdown
future: true

collections:
  speakers:
    output: true
    permalink: /:collection/:path:output_ext
  sponsors_premium:
    output: true
    permalink: /:collection/:path:output_ext
  sponsors_saison:
    output: true
    permalink: /:collection/:path:output_ext

